spring:
  datasource:
    url: jdbc:postgresql://database:5432/ridehub_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: jackson
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
