spring:
  datasource:
    url: jdbc:postgresql://RIDEHUB_DB_AR:5432/ridehub_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: jackson
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
sepay:
  webhook-secret: ${SEPAY_WEBHOOK_SECRET}

server:
  forward-headers-strategy: framework