networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24

volumes:
  jenkins-data-ridehub-app:
services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 2222:8080
      - 50000:50000
    networks:
      custom:
        ipv4_address: 192.168.61.15
    dns: 8.8.8.8
    domainname: codespaces.io
    hostname: jenkins
    restart: on-failure
    volumes:
      - jenkins-data-ridehub-app:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
